Document: gerrit
Title: Debian gerrit Manual
Author: <insert document author here>
Abstract: This manual describes what gerrit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gerrit/gerrit.sgml.gz

Format: postscript
Files: /usr/share/doc/gerrit/gerrit.ps.gz

Format: text
Files: /usr/share/doc/gerrit/gerrit.text.gz

Format: HTML
Index: /usr/share/doc/gerrit/html/index.html
Files: /usr/share/doc/gerrit/html/*.html
